# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.5

  # Don't check binstubs or gemfile
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*_helper.rb'
    - 'frontend/**/*'
    - 'vendor/**/*'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# Don't require a class comment
Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

# Require trailing commas for aguments
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Require trailing commas for multiline arrays
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Require trailing commas for multiline hashes
Style/TrailingCommaInHashLiteral:
  Enabled: false

# Allow but do not require modifier usage of if/unless
Style/IfUnlessModifier:
  Enabled: false

# Default Rails files have comment lines this long
Metrics/LineLength:
  Max: 120

# Disable this for this project for legacy reasons; test when changing
Style/DateTime:
  Enabled: false

# Allow *%i[…]
Lint/UnneededSplatExpansion:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false

# Be more flexible
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# The examples I see always use stabby lambdas
Style/Lambda:
  Enabled: false
