version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: firehose

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: firehose
          POSTGRES_PASSWORD: apppassword

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "frontend/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem update bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            sudo npm install -g ember-cli
            sudo chmod +x /usr/local/bin/yarn
            sudo yarn install
            cd frontend
            sudo yarn install

      - save_cache:
          paths:
            - node_modules
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "frontend/yarn.lock" }}
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "frontend/yarn.lock" }}

      # Database setup
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      # lint
      - run:
          name: lint
          command: |
            cd frontend
            yarn lint:js
            yarn lint:hbs

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            echo "testing rails"
            bundle exec rubocop
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
            cd frontend

            echo "testing ember"
            ember test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
